Bot realisation (INT-63)
wezzen/deeplay-camp-2024 pull request #33
Opened 2024-07-24 16:45 UTC by Krakaziabls

Пока что догружаю, что точно работает, есть вопросы. Кроме того, пока нет хода, боту нечего делать, написал с заглушкой

2024-07-26 10:05 UTC, BakinII requested changes

2024-07-26 10:05 UTC, BakinII commented on game/src/main/java/io/deeplay/camp/game/bots/RandomBot.java
> +        Random random = new Random();
ты каждый раз инициализируешь новый обьект рандома, инициализируй его 1 раз в конструкторе, а здесь просто обращайся к нему

2024-07-27 11:23 UTC, Krakaziabls commented on game/src/main/java/io/deeplay/camp/game/bots/RandomBot.java
> +        Random random = new Random();
Упустил! Спасибо!

2024-07-27 11:39 UTC, BakinII requested changes

2024-07-27 11:39 UTC, BakinII commented on game/src/main/java/io/deeplay/camp/game/bots/Bot.java
> +    public void getPlayerAction(final Move move, final String playerName) {
у бота есть свой экземпляр игры и он должен реагировать на события прилетающие ему от сервера/селфплея/гуишки и обновлять данные в своем экземпляре гейм

2024-07-27 12:20 UTC, BakinII requested changes

2024-07-27 12:20 UTC, BakinII commented on game/src/main/java/io/deeplay/camp/game/bots/RandomBot.java
> +    protected Cell getRandomCell(Cell[][] board) {
если у нас сейчас уже есть валидация доступных клеток, надо выбирать случайную клетку из доступных, а не из всех клеток поля

2024-07-29 09:20 UTC, closed without merging