fixField
wezzen/deeplay-camp-2024 pull request #7
Opened 2024-07-12 10:29 UTC by BakinII

изменил генерацию так как в старой версии была некоректная генерация

2024-07-12 10:58 UTC, wezzen reviewed
тесты нам нужно не просто чтобы они были. Сделай тест, в котором ты генерируешь игровое поле и потом проверь его, что оно зеркальное

2024-07-12 11:14 UTC, BakinII commented
> тесты нам нужно не просто чтобы они были. Сделай тест, в котором ты генерируешь игровое поле и потом проверь его, что оно зеркальное

окей, тесты доделаю, по поводу зеркальности, мы обсуждали что начало игры для игроков будет левый-нижний угол для первого игрока и правый верхний для второго, поэтому зеркальность смотрел относительно побочной диагонали

2024-07-12 12:30 UTC, wezzen commented on src/test/java/io/deeplay/camp/engine/entities/FieldTest.java
> +                    assertNotNull(field.getBoard()[field.getSize()-1-i][field.getSize()-1-j].planet);
{x,y) (y,x) не укажет симметрию в матрице?

2024-07-12 12:30 UTC, wezzen commented on src/test/java/io/deeplay/camp/engine/entities/FieldTest.java
> +                    assertNotNull(field.getBoard()[field.getSize()-1-i][field.getSize()-1-j].planet);
окей, ты найдешь две планеты на симметричных относительно диагонали клетках, а планеты могут быть разные

2024-07-12 12:30 UTC, wezzen commented on src/test/java/io/deeplay/camp/engine/entities/FieldTest.java
> +                    assertNotNull(field.getBoard()[field.getSize()-1-i][field.getSize()-1-j].planet);
сделай код почище

2024-07-13 08:13 UTC, wezzen requested changes

2024-07-13 08:13 UTC, wezzen commented on src/test/java/io/deeplay/camp/engine/entities/FieldTest.java
> -                    assertNotNull(field.getBoard()[field.getSize()-1-i][field.getSize()-1-j].planet);
как сравнить два объекта в java?)

2024-07-15 05:52 UTC, BakinII commented on src/test/java/io/deeplay/camp/engine/entities/FieldTest.java
> -                    assertNotNull(field.getBoard()[field.getSize()-1-i][field.getSize()-1-j].planet);
тут идея в том, что мы сравниваем только очки базовой защиты, так как у нас на планете помимо базовой защиты могут быть корабли и владелец планеты, можно переопределить equals(),  так чтобы метод смотрел только на очки защиты, но это может вызвать проблемы позднее

2024-07-15 07:55 UTC, wezzen commented on src/test/java/io/deeplay/camp/engine/entities/FieldTest.java
> -                    assertNotNull(field.getBoard()[field.getSize()-1-i][field.getSize()-1-j].planet);
идея любопытная, но так или иначе нужен метод сравнения. Завтра помимо очков добавите название планеты и тест этот уже будет неактуальным и даже неправильным

2024-07-16 05:40 UTC, wezzen approved these changes

2024-07-16 05:56 UTC, merged