fix: Переработал классы сущностей, оставил только требуемые методы
wezzen/deeplay-camp-2024 pull request #9
Opened 2024-07-14 22:26 UTC by Krakaziabls

Постарался оставить только необходимые методы/поля. Учел комментарий про оверхед

2024-07-15 14:50 UTC, BakinII requested changes
мне кажется нужен отдельная сущность - основной класс модели в котором будет поле, игроки, возможно это должен быть контроллер, в котором будет счетчик/цикл который будет обновлять поинты

2024-07-15 14:50 UTC, BakinII commented on src/main/java/io/deeplay/camp/engine/entities/Fleet.java
Мне кажется, что нужно обратная зависимость клетка-флот, не в экземпляре флота хранится клетка, а флот хранится внутри отдельной клетки

2024-07-15 14:50 UTC, BakinII commented on src/main/java/io/deeplay/camp/engine/entities/Fleet.java
хранение силы в отдельной переменной, которую надо постоянно апдейтить как будто не круто, проще сделать 1 метод который по вызову будет возвращать силу текущего флота

2024-07-17 04:19 UTC, wezzen approved these changes

2024-07-17 14:57 UTC, merged